### ISSUE TITLE
Failed to find function dmlab_connect in library!

### ISSUE THREAD

**Issue by alversafa** [deepmind/lab#171] opened 2019-10-14 22:47 UTC
Hi,

After running "bazel build -c opt //:deepmind_lab.so", I run "bazel run :python_random_agent --define headless=osmesa" and get the following output:

```
Failed to find function dmlab_connect in library!
Traceback (most recent call last):
  File "/network/home/alversaf/.cache/bazel/_bazel_alversaf/c78c672c9c47c1e9c2d9a08f489f56c4/execroot/org_deepmind_lab/bazel-out/k8-fastbuild/bin/python_random_agent.runfiles/org_deepmind_lab/python/random_agent.py", line 206, in <module>
    args.record, args.demo, args.demofiles, args.video)
  File "/network/home/alversaf/.cache/bazel/_bazel_alversaf/c78c672c9c47c1e9c2d9a08f489f56c4/execroot/org_deepmind_lab/bazel-out/k8-fastbuild/bin/python_random_agent.runfiles/org_deepmind_lab/python/random_agent.py", line 155, in run
    env = deepmind_lab.Lab(level, ['RGB_INTERLEAVED'], config=config)
RuntimeError: Failed to connect RL API
```

What should I do? Thanks! (By the way, I am running bazel through a singularity container.)

**Comment by tkoeppe** [comment] 2019-10-15 23:15
(Note that `bazel build -c opt //:deepmind_lab.so` has no effect here, since your second build a) runs under different flags and thus discards the previous outputs, and b) would build all required dependencies anyway.)

**Comment by alversafa** [comment] 2019-10-15 23:29
Thanks. Yeah, just realized that. But doesn't make any difference in the output.

**Comment by tkoeppe** [comment] 2019-10-15 23:31
I can reproduce the problem. Very strange! I'll investigate.

**Comment by tkoeppe** [comment] 2019-10-15 23:42
This should be fixed by 61d81da2833c73389c58704a955f1945851c49e0.

We must have previously discovered this, since e.g. https://github.com/deepmind/lab/blob/master/deepmind/engine/BUILD#L195 contains the `alwayslink` setting for the same reason. I vaguely suspect that some details of Bazel have changed (for the stricter) so that we got away with this in the past.

**Closed by tkoeppe** 2019-10-15 23:42 UTC

**Comment by tkoeppe** [comment] 2019-10-16 00:07
(And I submitted 3aacfe6f2d083d6208fd75d56eef825a3e9eaf76 to improve the CI to test for this sort of problem.)

**Comment by alversafa** [comment] 2019-10-16 00:48
The problem is solved! Thank you!

**Comment by tkoeppe** [comment] 2019-10-16 10:22
(And 6b3dba017e26e7124cd86e030d0bd045ab6bdb57 makes the Travis test run the example, too.)

**Comment by alversafa** [comment] 2021-11-13 09:37
Hi, I really do not remember how I solved it as a long time has passed.
