### ISSUE TITLE
Pip package not working with python 3

### ISSUE THREAD

**Issue by camigord** [deepmind/lab#92] opened 2018-04-09 13:50 UTC
Hi,

I am having some problems when trying to build/install Deepmind Lab as a pip package with Python 3. Currently I am capable of generating the package .whl file (`DeepMind_Lab-1.0-py3-none-any.whl`) and installing in a conda environment, but I am getting the following error when importing the `deepmind_lab` module:

```
deepmind_lab.so: undefined symbol: PyCObject_Type
```
Any suggestions about how to fix this?

Thanks,

**Comment by tkoeppe** [comment] 2018-04-09 14:45
Hm, I haven't tested the PIP building yet, but it looks like a linker error. I'd try changing the settings in python.BUILD to point at the Python 3 library maybe?

**Comment by camigord** [comment] 2018-04-10 15:26
Hi, thanks for the reply. 
I'm trying to install the package in a conda environment, so here is what I tried:
- I modified the WORKSPACE file in order to set the path to anaconda
```
new_local_repository(
    name = "python_system",
    build_file = "python.BUILD",
    path = "/home/anaconda3",
)
```
- I modified python.BUILD in order to point to the python3 version installed in anaconda.

```
cc_library(
    name = "python",
    hdrs = glob(["include/python3.6m/*.h"]),
    includes = ["include/python3.6m"],
    visibility = ["//visibility:public"],
)
```

However, after building and installing the package, I get the following error when trying to import deepmind_lab:

```
python3.6/site-packages/deepmind_lab/__init__.py in <module>()
      imp.load_dynamic(__name__, pkg_resources.resource_filename(__name__, 'deepmind_lab.so'))

python3.6/imp.py in load_dynamic(name, path, file)
    341         spec = importlib.machinery.ModuleSpec(name=name, loader=loader, origin=path)
--> 343         return _load(spec)

ImportError: numpy.core.multiarray failed to import
```

I don't understand what's going on, given that numpy is properly installed. Is there anywhere else where I should modify the paths before building?

Thanks,

**Comment by joabim** [comment] 2018-04-10 15:31
I too have the same problem regarding this - I can build the pip package but not import the `deepmind_lab` module. I'm currently stuck with the `numpy.core.multiarray failed to import` error as well (using my anaconda3 root as path in the `python_system` build rule in `WORKSPACES`)

**Comment by charlesbeattie** [comment] 2018-04-10 15:44
Have you tried importing numpy before importing deepmind_lab module?

**Comment by camigord** [comment] 2018-04-10 15:47
yes, same problem.

**Comment by charlesbeattie** [comment] 2018-04-10 16:17
Can you make sure you have the latest version of numpy?
On my system:
```sh
$ python3 -c "import numpy;print(numpy.__version__);print(numpy.__file__)"
1.12.1
/usr/lib/python3/dist-packages/numpy/__init__.py
```

**Comment by camigord** [comment] 2018-04-10 16:31
I get the following:
```
print(numpy.__version__)
1.14.2

print(numpy.__file__)
~/anaconda3/envs/conda_env_test/lib/python3.6/site-packages/numpy/__init__.py
```

**Comment by camigord** [comment] 2018-04-10 16:34
I tried to install the package locally, thinking that there may be some linking issues with Anaconda, but I get the same error after modifying the BUILD files mentioned above (pointing the files to /urs/include/python3.6/...)

**Comment by tkoeppe** [comment] 2018-04-16 10:26
Random thought, looking at build_pip_package.sh: Have you specified a `PYTHON_BIN_PATH` environment variable? E.g.:

    PYTHON_BIN_PATH=/usr/bin/python3 bazel build python/pip_package:build_pip_package

**Comment by joabim** [comment] 2018-04-16 14:02
I've tried what you suggested (hardcoding it my anaconda python bin path) but I'm getting the numpy.core.multiarray import problem

**Comment by tkoeppe** [comment] 2018-05-02 01:45
Oh, wait, it says on the front page: you need Numpy >= 1.8.

**Comment by gchlodzinski** [comment] 2018-05-08 17:55
Hi, I am getting the same error (with the same configuration - Python3.6 installed via Anaconda) even when running command:
bazel run //:python_random_agent
....
INFO: Running command line: bazel-bin/python_random_agent
ImportError: numpy.core.multiarray failed to import
....

So I think this problem is NOT related strictly to pip building but rather general Lab compatibility with Python3 or Anaconda distribution.

**Comment by floringogianu** [comment] 2018-05-10 15:25
I tried building with the following changes in the bazel config files but I am getting the same `numpy` import error (`numpy 1.14.2` is installed in this env):

```diff
diff --git a/BUILD b/BUILD
index 9e274c5..3972e07 100644
--- a/BUILD
+++ b/BUILD
@@ -984,6 +984,7 @@ py_binary(
     data = [":deepmind_lab.so"],
     main = "python/random_agent.py",
     visibility = ["//python/tests:__subpackages__"],
+    default_python_version = "PY3"
 )
 
 LOAD_TEST_SCRIPTS = [
diff --git a/WORKSPACE b/WORKSPACE
index fa8da47..967c712 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -91,5 +91,5 @@ new_local_repository(
 new_local_repository(
     name = "python_system",
     build_file = "python.BUILD",
-    path = "/usr",
+    path = "/home/florin/Tools/miniconda3/envs/torch30",
 )
diff --git a/python.BUILD b/python.BUILD
index f0b3f9a..627bdc1 100644
--- a/python.BUILD
+++ b/python.BUILD
@@ -5,7 +5,7 @@
 
 cc_library(
     name = "python",
-    hdrs = glob(["include/python2.7/*.h"]),
-    includes = ["include/python2.7"],
+    hdrs = glob(["include/python3.6m/*.h"]),
+    includes = ["include/python3.6m"],
     visibility = ["//visibility:public"],
 )
```
The output of `bazel run //:python_random_agent`:
```
INFO: Elapsed time: 52.883s, Critical Path: 21.54s
INFO: 706 processes: 705 linux-sandbox, 1 local.
INFO: Build completed successfully, 715 total actions

INFO: Running command line: bazel-out/k8-py3-fastbuild/bin/python_random_agent
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "/home/florin/.cache/bazel/_bazel_florin/329274937dbc60c7c6c49b959689f873/execroot/org_deepmind_lab/bazel-out/k8-py3-fastbuild/bin/python_random_agent.runfiles/org_deepmind_lab/python/random_agent.py", line 26, in <module>
    import deepmind_lab
ImportError: numpy.core.multiarray failed to import
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

**Comment by tkoeppe** [comment] 2018-05-20 22:05
Duplicate of #96.

**Closed by tkoeppe** 2018-05-20 22:05 UTC
