### ISSUE TITLE
Video and game is mirror on Y axis

### ISSUE THREAD

**Issue by talregev** [deepmind/lab#136] opened 2019-02-17 22:56 UTC
I create a deepmind lab environment on google colaboratory. 
https://colab.research.google.com/drive/1P4l_iFbzRGdMsnnmyAlWhJjqLY7qIWWE

I run the random agent:
`bazel run -c opt :python_random_agent`
And the video was created as Y mirror axis. 
Can you fix it?

**Comment by talregev** [comment] 2019-02-17 22:56
Can you add dqn train example?

**Comment by tkoeppe** [comment] 2019-02-18 10:30
This is a duplicate of #104.

**Closed by tkoeppe** 2019-02-18 10:30 UTC
